## exception

```c
PyObject* PyEval_EvalFrameEx(PyFrameObject *f)
{
    for (;;) {
        //巨大的switch语句
        if (why == WHY_NOT) {
            if (err == 0 && x != NULL) {
                    continue; //没有异常情况发生，执行下一条字节码指令
            }
            //设置why，通知虚拟机，异常发生了
            why = WHY_EXCEPTION;
            x = Py_None;
            err = 0;
        }
        
        if (why == WHY_EXCEPTION) {
            //创建traceback对象
            PyTraceBack_Here(f);
            if (tstate->c_tracefunc != NULL)
                call_exc_trace(tstate->c_tracefunc, tstate->c_traceobj, f);
        }
        
        //尝试捕捉异常
        if (why != WHY_NOT)//[1]
            break;
    } /* main loop */
    
    if (why != WHY_RETURN)
        retval = NULL;//[2] : 利用retval通知前一个栈帧有异常出现
        
    //[3] : 将线程状态对象中的活动栈帧设置为当前栈帧的上一个栈帧，完成栈帧回退的动作
    tstate->frame = f->f_back;
    return retval;
}
```